

  CREATE TABLE  CADENAHOTELERA 
   (	IDCADENAHOTELERA NUMBER, 
	NOMBRECADENAHOTELERA VARCHAR2(40 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;

  CREATE UNIQUE INDEX  CADENAHOTELERA_PK ON  CADENAHOTELERA (IDCADENAHOTELERA) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE  CADENAHOTELERA MODIFY (NOMBRECADENAHOTELERA NOT NULL ENABLE);
  ALTER TABLE  CADENAHOTELERA MODIFY (IDCADENAHOTELERA NOT NULL ENABLE);
  ALTER TABLE  CADENAHOTELERA ADD CONSTRAINT CADENAHOTELERA_PK PRIMARY KEY (IDCADENAHOTELERA)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE TBSPROD  ENABLE;
