CREATE TABLE CARACTERISTICAADICIONAL 
   (	IDCARACTERISTICA NUMBER, 
	LIMITE NUMBER, 
	DCTO NUMBER(*,0), 
	DESCRIPCION VARCHAR2(200 BYTE), 
	IDSERVICIOCOMP NUMBER, 
	IDSERVICIOALOJA NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX CARACTERISTICAADICIONAL_PK ON CARACTERISTICAADICIONAL (IDCARACTERISTICA) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE CARACTERISTICAADICIONAL MODIFY (DCTO NOT NULL ENABLE);
  ALTER TABLE CARACTERISTICAADICIONAL MODIFY (LIMITE NOT NULL ENABLE);
  ALTER TABLE CARACTERISTICAADICIONAL MODIFY (IDCARACTERISTICA NOT NULL ENABLE);
  ALTER TABLE CARACTERISTICAADICIONAL ADD CONSTRAINT FK_LIMITE CHECK (LIMITE > 0) ENABLE;
  ALTER TABLE CARACTERISTICAADICIONAL ADD CONSTRAINT CK_DCTO CHECK (DCTO BETWEEN 0 AND 1) ENABLE;
  ALTER TABLE CARACTERISTICAADICIONAL ADD CONSTRAINT CARACTERISTICAADICIONAL_PK PRIMARY KEY (IDCARACTERISTICA)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD  ENABLE;


  ALTER TABLE CARACTERISTICAADICIONAL ADD CONSTRAINT FK_SERVICIOALOJA FOREIGN KEY (IDSERVICIOALOJA)
	  REFERENCES SERVICIOALOJAMIENTO (IDSERVICIOALOJAMIENTO) ENABLE;
  ALTER TABLE CARACTERISTICAADICIONAL ADD CONSTRAINT FK_SERVICIODECARACTERISTICA FOREIGN KEY (IDSERVICIOCOMP)
	  REFERENCES SERVICIOHOTELCOMPLEMENTARIO (IDSCOMPLEMENTARIO) ENABLE;
