CREATE TABLE CONVENCIONHABITACION 
   (	IDCONVENCION NUMBER, 
	IDHABITACION NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX CONVENCIONHABITACION_PK ON CONVENCIONHABITACION (IDCONVENCION, IDHABITACION) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE CONVENCIONHABITACION MODIFY (IDHABITACION NOT NULL ENABLE);
  ALTER TABLE CONVENCIONHABITACION MODIFY (IDCONVENCION NOT NULL ENABLE);
  ALTER TABLE CONVENCIONHABITACION ADD CONSTRAINT CONVENCIONHABITACION_PK PRIMARY KEY (IDCONVENCION, IDHABITACION)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD  ENABLE;



  ALTER TABLE CONVENCIONHABITACION ADD CONSTRAINT FK_LAHABITACION1 FOREIGN KEY (IDHABITACION)
	  REFERENCES HABITACION (IDHABITACION) ENABLE;
