
  CREATE TABLE CONVENCIONSALON 
   (	IDCONVENCION NUMBER, 
	IDSALON NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;

  ALTER TABLE CONVENCIONSALON ADD CONSTRAINT FKCONVEN FOREIGN KEY (IDCONVENCION)
	  REFERENCES CONVENCION (IDCONVENCION) ENABLE;
  ALTER TABLE CONVENCIONSALON ADD CONSTRAINT FKSALON FOREIGN KEY (IDSALON)
	  REFERENCES SALON (IDSERVICIO) ENABLE;
