

  CREATE TABLE CONVENCIONRESTBARCAFETERIA 
   (	IDCONVENCION NUMBER, 
	IDSERVICIOI NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX CONVENCIONRESTBARCAFETERIA_PK ON CONVENCIONRESTBARCAFETERIA (IDCONVENCION, IDSERVICIOI) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE CONVENCIONRESTBARCAFETERIA MODIFY (IDSERVICIOI NOT NULL ENABLE);
  ALTER TABLE CONVENCIONRESTBARCAFETERIA MODIFY (IDCONVENCION NOT NULL ENABLE);
  ALTER TABLE CONVENCIONRESTBARCAFETERIA ADD CONSTRAINT CONVENCIONRESTBARCAFETERIA_PK PRIMARY KEY (IDCONVENCION, IDSERVICIOI)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD  ENABLE;


  ALTER TABLE CONVENCIONRESTBARCAFETERIA ADD CONSTRAINT FKCONVENCION1 FOREIGN KEY (IDCONVENCION)
	  REFERENCES CONVENCION (IDCONVENCION) ENABLE;
  ALTER TABLE CONVENCIONRESTBARCAFETERIA ADD CONSTRAINT FKSERV FOREIGN KEY (IDSERVICIOI)
	  REFERENCES SERVICIOHOTELCOMPLEMENTARIO (IDSCOMPLEMENTARIO) ENABLE;
