CREATE TABLE CONVENCION 
   (	IDCONVENCION NUMBER, 
	IDHOTEL NUMBER, 
	NUMPARTICIPANTES NUMBER, 
	NOMBRECONVENCION VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  ALTER TABLE CONVENCION MODIFY (NUMPARTICIPANTES NOT NULL ENABLE);
  ALTER TABLE CONVENCION MODIFY (IDHOTEL NOT NULL ENABLE);
  ALTER TABLE CONVENCION MODIFY (IDCONVENCION NOT NULL ENABLE);


  ALTER TABLE CONVENCION ADD CONSTRAINT FK_HOTELCONVENCION FOREIGN KEY (IDHOTEL)
	  REFERENCES HOTEL (IDHOTEL) ENABLE;
  ALTER TABLE CONVENCION ADD CONSTRAINT FK_USUARIO FOREIGN KEY (IDCONVENCION)
	  REFERENCES USUARIO (IDUSUARIO) ENABLE;
