CREATE TABLE CUENTAALOJAMIENTO 
   (	IDCUENTA NUMBER, 
	IDSERVICIOALOJAMIENTO NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX CUENTAALOJAMIENTO_PK ON CUENTAALOJAMIENTO (IDCUENTA, IDSERVICIOALOJAMIENTO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE CUENTAALOJAMIENTO MODIFY (IDSERVICIOALOJAMIENTO NOT NULL ENABLE);
  ALTER TABLE CUENTAALOJAMIENTO MODIFY (IDCUENTA NOT NULL ENABLE);
  ALTER TABLE CUENTAALOJAMIENTO ADD CONSTRAINT CUENTAALOJAMIENTO_PK PRIMARY KEY (IDCUENTA, IDSERVICIOALOJAMIENTO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD  ENABLE;


  ALTER TABLE CUENTAALOJAMIENTO ADD CONSTRAINT FKCUENTA FOREIGN KEY (IDCUENTA)
	  REFERENCES CUENTA (IDCUENTA) ENABLE;
  ALTER TABLE CUENTAALOJAMIENTO ADD CONSTRAINT FKSERVA FOREIGN KEY (IDSERVICIOALOJAMIENTO)
	  REFERENCES SERVICIOALOJAMIENTO (IDSERVICIOALOJAMIENTO) ENABLE;
