CREATE TABLE CUENTA 
   (	IDCUENTA NUMBER, 
	VALOR NUMBER, 
	METODODEPAGO VARCHAR2(20 BYTE), 
	IDPLANCONSUMO NUMBER, 
	IDCLIENTE NUMBER, 
	IDRESERVA NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;

  CREATE UNIQUE INDEX CUENTA_PK ON CUENTA (IDCUENTA) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;

  ALTER TABLE CUENTA MODIFY (IDCLIENTE NOT NULL ENABLE);
  ALTER TABLE CUENTA MODIFY (METODODEPAGO NOT NULL ENABLE);
  ALTER TABLE CUENTA MODIFY (VALOR NOT NULL ENABLE);
  ALTER TABLE CUENTA MODIFY (IDCUENTA NOT NULL ENABLE);
  ALTER TABLE CUENTA ADD CONSTRAINT CUENTA_PK PRIMARY KEY (IDCUENTA)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD  ENABLE;
  ALTER TABLE CUENTA ADD CONSTRAINT CK_VALOR CHECK (VALOR > 0) ENABLE;


  ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTACLIENTE FOREIGN KEY (IDCLIENTE)
	  REFERENCES USUARIO (IDUSUARIO) ENABLE;
  ALTER TABLE CUENTA ADD CONSTRAINT FK_PLANENCUENTA FOREIGN KEY (IDPLANCONSUMO)
	  REFERENCES PLAN (IDPLAN) ENABLE;
  ALTER TABLE CUENTA ADD CONSTRAINT FK_RESERV FOREIGN KEY (IDRESERVA)
	  REFERENCES RESERVA (IDRESERVA) ENABLE;
