CREATE TABLE DOTACIONHABITACION 
   (	IDDOTACION NUMBER, 
	IDHABITACION NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX DOTACIONHABITACION_PK ON DOTACIONHABITACION (IDDOTACION, IDHABITACION) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE DOTACIONHABITACION MODIFY (IDHABITACION NOT NULL ENABLE);
  ALTER TABLE DOTACIONHABITACION MODIFY (IDDOTACION NOT NULL ENABLE);
  ALTER TABLE DOTACIONHABITACION ADD CONSTRAINT DOTACIONHABITACION_PK PRIMARY KEY (IDDOTACION, IDHABITACION)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD  ENABLE;



  ALTER TABLE DOTACIONHABITACION ADD CONSTRAINT FK_DOTACION FOREIGN KEY (IDDOTACION)
	  REFERENCES DOTACION (IDDOTACION) ENABLE;
  ALTER TABLE DOTACIONHABITACION ADD CONSTRAINT FK_LAHABITACION FOREIGN KEY (IDHABITACION)
	  REFERENCES HABITACION (IDHABITACION) ENABLE;
