CREATE TABLE HORARIO 
   (	IDHORARIO NUMBER, 
	HORAINICIO NUMBER, 
	HORAFINAL NUMBER, 
	FECHAINICIO DATE, 
	FECHAFINAL DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX HORARIO_PK ON HORARIO (IDHORARIO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  ALTER TABLE HORARIO MODIFY (IDHORARIO NOT NULL ENABLE);
  ALTER TABLE HORARIO ADD CONSTRAINT HORARIO_PK PRIMARY KEY (IDHORARIO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD  ENABLE;
  ALTER TABLE HORARIO ADD CONSTRAINT FK_HORAFINAL CHECK (HORAFINAL > 0) ENABLE;
  ALTER TABLE HORARIO ADD CONSTRAINT FK_FECHAFINALMAYORINICIAL CHECK (FECHAINICIO < FECHAFINAL) ENABLE;
  ALTER TABLE HORARIO ADD CONSTRAINT CK_HORAINICIO CHECK (HORAINICIO > 0) ENABLE;
