--------------------------------------------------------
--  File created - Sunday-April-14-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE HOTEL 
   (	NOMBREHOTEL VARCHAR2(30 BYTE), 
	ESTRELLAS NUMBER, 
	CIUDAD VARCHAR2(30 BYTE), 
	PAIS VARCHAR2(30 BYTE), 
	IDCADENAHOTELERA NUMBER, 
	IDHOTEL NUMBER, 
	CANTHABITACIONES NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;
--------------------------------------------------------
--  DDL for Index HOTEL_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX HOTEL_PK1 ON HOTEL (IDHOTEL) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;
--------------------------------------------------------
--  Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE HOTEL MODIFY (IDCADENAHOTELERA NOT NULL ENABLE);
  ALTER TABLE HOTEL MODIFY (IDHOTEL NOT NULL ENABLE);
  ALTER TABLE HOTEL MODIFY (NOMBREHOTEL NOT NULL ENABLE);
  ALTER TABLE HOTEL MODIFY (PAIS NOT NULL ENABLE);
  ALTER TABLE HOTEL MODIFY (CIUDAD NOT NULL ENABLE);
  ALTER TABLE HOTEL MODIFY (ESTRELLAS NOT NULL ENABLE);
  ALTER TABLE HOTEL ADD CONSTRAINT HOTEL_PK PRIMARY KEY (IDHOTEL)
  USING INDEX (CREATE UNIQUE INDEX HOTEL_PK1 ON HOTEL (IDHOTEL) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD )  ENABLE;
  ALTER TABLE HOTEL ADD CONSTRAINT CK_ESTRELLAS CHECK (ESTRELLAS BETWEEN 1 AND 5) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE HOTEL ADD CONSTRAINT FK_CADENAHOTELERA FOREIGN KEY (IDCADENAHOTELERA)
	  REFERENCES CADENAHOTELERA (IDCADENAHOTELERA) ENABLE;
