CREATE TABLE  HOTEL 
   (	NOMBREHOTEL VARCHAR2(30 BYTE), 
	ESTRELLAS NUMBER, 
	CIUDAD VARCHAR2(30 BYTE), 
	PAIS VARCHAR2(30 BYTE), 
	IDCADENAHOTELERA NUMBER, 
	IDHOTEL NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX   HOTEL_PK ON  HOTEL (IDHOTEL) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE  HOTEL MODIFY (IDCADENAHOTELERA NOT NULL ENABLE);
  ALTER TABLE  HOTEL MODIFY (IDHOTEL NOT NULL ENABLE);
  ALTER TABLE  HOTEL MODIFY (NOMBREHOTEL NOT NULL ENABLE);
  ALTER TABLE  HOTEL MODIFY (PAIS NOT NULL ENABLE);
  ALTER TABLE  HOTEL MODIFY (CIUDAD NOT NULL ENABLE);
  ALTER TABLE  HOTEL MODIFY (ESTRELLAS NOT NULL ENABLE);
  ALTER TABLE  HOTEL ADD CONSTRAINT HOTEL_PK PRIMARY KEY (IDHOTEL)
  USING INDEX (CREATE UNIQUE INDEX   HOTEL_PK ON  HOTEL (IDHOTEL) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE TBSPROD )  ENABLE;
  ALTER TABLE  HOTEL ADD CONSTRAINT CK_ESTRELLAS CHECK (ESTRELLAS BETWEEN 1 AND 5) ENABLE;


  ALTER TABLE  HOTEL ADD CONSTRAINT FK_CADENAHOTELERA FOREIGN KEY (IDCADENAHOTELERA)
	  REFERENCES  CADENAHOTELERA (IDCADENAHOTELERA) ENABLE;
