CREATE TABLE REGISTRO 
   (	IDREGISTRO NUMBER, 
	IDRESERVA NUMBER, 
	ESTADOCHECKIN CHAR(1 BYTE), 
	ESTADOCHECKOUT CHAR(1 BYTE), 
	IDREGISTRADOR NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX REGISTRO_PK ON REGISTRO (IDREGISTRO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  ALTER TABLE REGISTRO MODIFY (IDRESERVA NOT NULL ENABLE);
  ALTER TABLE REGISTRO MODIFY (IDREGISTRO NOT NULL ENABLE);
  ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_PK PRIMARY KEY (IDREGISTRO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD  ENABLE;
  ALTER TABLE REGISTRO ADD CONSTRAINT CK_OUT CHECK (ESTADOCHECKOUT IN ('E', 'F')) ENABLE;
  ALTER TABLE REGISTRO ADD CONSTRAINT CK_IN CHECK (ESTADOCHECKIN IN ('E', 'F')) ENABLE;


  ALTER TABLE REGISTRO ADD CONSTRAINT FK_RESERVA FOREIGN KEY (IDRESERVA)
	  REFERENCES RESERVA (IDRESERVA) ENABLE;
  ALTER TABLE REGISTRO ADD CONSTRAINT FK_USUARIOREGIS FOREIGN KEY (IDREGISTRADOR)
	  REFERENCES USUARIO (IDUSUARIO) ENABLE;
