CREATE TABLE RESERVA 
   (	IDRESERVA NUMBER, 
	ABONO NUMBER, 
	IDHABITACION NUMBER, 
	IDHORARIO NUMBER, 
	IDCLIENTE NUMBER, 
	IDHOTEL NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX RESERVA_PK ON RESERVA (IDRESERVA) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  ALTER TABLE RESERVA MODIFY (IDCLIENTE NOT NULL ENABLE);
  ALTER TABLE RESERVA MODIFY (IDHORARIO NOT NULL ENABLE);
  ALTER TABLE RESERVA MODIFY (IDHABITACION NOT NULL ENABLE);
  ALTER TABLE RESERVA MODIFY (IDRESERVA NOT NULL ENABLE);
  ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_PK PRIMARY KEY (IDRESERVA)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD  ENABLE;
  ALTER TABLE RESERVA ADD CONSTRAINT CK_ABONO CHECK (ABONO > 0) ENABLE;


  ALTER TABLE RESERVA ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (IDCLIENTE)
	  REFERENCES USUARIO (IDUSUARIO) ENABLE;
  ALTER TABLE RESERVA ADD CONSTRAINT FK_HABITACION FOREIGN KEY (IDHABITACION)
	  REFERENCES HABITACION (IDHABITACION) ENABLE;
  ALTER TABLE RESERVA ADD CONSTRAINT FK_HORARIORESERVA FOREIGN KEY (IDHORARIO)
	  REFERENCES HORARIO (IDHORARIO) ENABLE;
  ALTER TABLE RESERVA ADD CONSTRAINT FK_HOTELRESERVA FOREIGN KEY (IDHOTEL)
	  REFERENCES HOTEL (IDHOTEL) ENABLE;
