CREATE TABLE SERVICIOALIMENTACION 
   (	IDSERVICIO NUMBER, 
	NOMBRESERVICIO VARCHAR2(20 BYTE), 
	ESTILO VARCHAR2(20 BYTE), 
	CAPACIDAD NUMBER, 
	TIPO VARCHAR2(20 BYTE), 
	ESCONSUMOHABITACION CHAR(1 BYTE), 
	IDHORARIO NUMBER, 
	DESCRIPCION VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX SERVICIOALIMENTACION_PK ON SERVICIOALIMENTACION (IDSERVICIO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  ALTER TABLE SERVICIOALIMENTACION MODIFY (IDHORARIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOALIMENTACION MODIFY (ESCONSUMOHABITACION NOT NULL ENABLE);
  ALTER TABLE SERVICIOALIMENTACION MODIFY (TIPO NOT NULL ENABLE);
  ALTER TABLE SERVICIOALIMENTACION MODIFY (CAPACIDAD NOT NULL ENABLE);
  ALTER TABLE SERVICIOALIMENTACION MODIFY (ESTILO NOT NULL ENABLE);
  ALTER TABLE SERVICIOALIMENTACION MODIFY (NOMBRESERVICIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOALIMENTACION MODIFY (IDSERVICIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOALIMENTACION ADD CONSTRAINT SERVICIOALIMENTACION_PK PRIMARY KEY (IDSERVICIO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD  ENABLE;


  ALTER TABLE SERVICIOALIMENTACION ADD CONSTRAINT SERVICIOALIMENTACION_FK1 FOREIGN KEY (IDSERVICIO)
	  REFERENCES SERVICIOALIMENTACION (IDSERVICIO) ENABLE;
