CREATE TABLE SERVICIOINCLUIDO 
   (	IDSERVICIO NUMBER, 
	NOMBRE VARCHAR2(30 BYTE), 
	CAPACIDAD NUMBER, 
	IDHOTEL NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX SERVICIOINCLUIDO_PK ON SERVICIOINCLUIDO (IDSERVICIO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  ALTER TABLE SERVICIOINCLUIDO MODIFY (IDHOTEL NOT NULL ENABLE);
  ALTER TABLE SERVICIOINCLUIDO MODIFY (CAPACIDAD NOT NULL ENABLE);
  ALTER TABLE SERVICIOINCLUIDO MODIFY (NOMBRE NOT NULL ENABLE);
  ALTER TABLE SERVICIOINCLUIDO MODIFY (IDSERVICIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOINCLUIDO ADD CONSTRAINT SERVICIOINCLUIDO_PK PRIMARY KEY (IDSERVICIO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD  ENABLE;


  ALTER TABLE SERVICIOINCLUIDO ADD CONSTRAINT FK_IDHOTELSERVICIO FOREIGN KEY (IDHOTEL)
	  REFERENCES HOTEL (IDHOTEL) ENABLE;
  ALTER TABLE SERVICIOINCLUIDO ADD CONSTRAINT PKFK FOREIGN KEY (IDSERVICIO)
	  REFERENCES SERVICIOHOTELCOMPLEMENTARIO (IDSCOMPLEMENTARIO) ENABLE;
