CREATE TABLE SERVICIOLAVANDERIA 
   (	IDSERVICIO NUMBER, 
	NOMBRESERVICIO VARCHAR2(20 BYTE), 
	DESCRIPCION VARCHAR2(200 BYTE), 
	TIPO VARCHAR2(20 BYTE), 
	COSTOUNITARIO NUMBER, 
	CANTUNIDADES NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX SERVICIOLAVANDERIA_PK ON SERVICIOLAVANDERIA (IDSERVICIO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;


  ALTER TABLE SERVICIOLAVANDERIA MODIFY (CANTUNIDADES NOT NULL ENABLE);
  ALTER TABLE SERVICIOLAVANDERIA MODIFY (COSTOUNITARIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOLAVANDERIA MODIFY (TIPO NOT NULL ENABLE);
  ALTER TABLE SERVICIOLAVANDERIA MODIFY (DESCRIPCION NOT NULL ENABLE);
  ALTER TABLE SERVICIOLAVANDERIA MODIFY (NOMBRESERVICIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOLAVANDERIA MODIFY (IDSERVICIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOLAVANDERIA ADD CONSTRAINT SERVICIOLAVANDERIA_PK PRIMARY KEY (IDSERVICIO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD  ENABLE;
  ALTER TABLE SERVICIOLAVANDERIA ADD CONSTRAINT FK_COSTOUNITARIO CHECK (COSTOUNITARIO >0) ENABLE;
  ALTER TABLE SERVICIOLAVANDERIA ADD CONSTRAINT CK_CANTUNIDADES CHECK (CANTUNIDADES>0) ENABLE;


  ALTER TABLE SERVICIOLAVANDERIA ADD CONSTRAINT FKSERVI FOREIGN KEY (IDSERVICIO)
	  REFERENCES SERVICIOHOTELCOMPLEMENTARIO (IDSCOMPLEMENTARIO) ENABLE;
