--------------------------------------------------------
--  File created - Monday-April-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICIOHOTELCOMPLEMENTARIO
--------------------------------------------------------

  CREATE TABLE SERVICIOHOTELCOMPLEMENTARIO 
   (	IDSCOMPLEMENTARIO NUMBER, 
	NOMBRESERVICIO VARCHAR2(50 BYTE), 
	IDHOTEL NUMBER, 
	IDHORARIO NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;
--------------------------------------------------------
--  DDL for Index SERVICIOHOTELCOMPLEMENTARI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX SERVICIOHOTELCOMPLEMENTARI_PK ON SERVICIOHOTELCOMPLEMENTARIO (IDSCOMPLEMENTARIO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD ;
--------------------------------------------------------
--  Constraints for Table SERVICIOHOTELCOMPLEMENTARIO
--------------------------------------------------------

  ALTER TABLE SERVICIOHOTELCOMPLEMENTARIO MODIFY (NOMBRESERVICIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOHOTELCOMPLEMENTARIO MODIFY (IDSCOMPLEMENTARIO NOT NULL ENABLE);
  ALTER TABLE SERVICIOHOTELCOMPLEMENTARIO ADD CONSTRAINT SERVICIOHOTELCOMPLEMENTARI_PK PRIMARY KEY (IDSCOMPLEMENTARIO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TBSPROD  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICIOHOTELCOMPLEMENTARIO
--------------------------------------------------------

  ALTER TABLE SERVICIOHOTELCOMPLEMENTARIO ADD CONSTRAINT FKHORARIO1 FOREIGN KEY (IDHORARIO)
	  REFERENCES HORARIO (IDHORARIO) ENABLE;
  ALTER TABLE SERVICIOHOTELCOMPLEMENTARIO ADD CONSTRAINT FK_HOTEL FOREIGN KEY (IDHOTEL)
	  REFERENCES HOTEL (IDHOTEL) ENABLE;
