 CREATE TABLE  SERVICIOALOJAMIENTOHABITACION 
   (	IDHABITACION NUMBER, 
	IDSERVICIOALOJAMIENTO NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX  SERVICIOALOJAMIENTOHABITAC_PK ON  SERVICIOALOJAMIENTOHABITACION (IDHABITACION, IDSERVICIOALOJAMIENTO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE  SERVICIOALOJAMIENTOHABITACION MODIFY (IDSERVICIOALOJAMIENTO NOT NULL ENABLE);
  ALTER TABLE  SERVICIOALOJAMIENTOHABITACION MODIFY (IDHABITACION NOT NULL ENABLE);
  ALTER TABLE  SERVICIOALOJAMIENTOHABITACION ADD CONSTRAINT SERVICIOALOJAMIENTOHABITAC_PK PRIMARY KEY (IDHABITACION, IDSERVICIOALOJAMIENTO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD  ENABLE;


  ALTER TABLE  SERVICIOALOJAMIENTOHABITACION ADD CONSTRAINT FK_HABITACION FOREIGN KEY (IDHABITACION)
	  REFERENCES  HABITACION (IDHABITACION) ENABLE;
  ALTER TABLE  SERVICIOALOJAMIENTOHABITACION ADD CONSTRAINT FK_SERVICIOALOJAMIENTO FOREIGN KEY (IDSERVICIOALOJAMIENTO)
	  REFERENCES  SERVICIOALOJAMIENTO (IDSERVICIOALOJAMIENTO) ENABLE;
