

  CREATE TABLE TIPOHABITACION 
   (	NOMBRETIPO VARCHAR2(20 BYTE), 
	DESCRIPCION VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBSPROD ;


  CREATE UNIQUE INDEX TIPOHABITACION_PK ON TIPOHABITACION (NOMBRETIPO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD ;


  ALTER TABLE TIPOHABITACION ADD CONSTRAINT TIPOHABITACION_PK PRIMARY KEY (NOMBRETIPO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE TBSPROD  ENABLE;
  ALTER TABLE TIPOHABITACION MODIFY (DESCRIPCION NOT NULL ENABLE);
  ALTER TABLE TIPOHABITACION MODIFY (NOMBRETIPO NOT NULL ENABLE);
