SELECT shc.idscomplementario, shc.nombreservicio, cu.valor, COUNT(cs.IDSERVICIOCOMPLEMENTARIO) AS CANTVECES, hor.FECHAINICIO, hor.FECHAFINAL, reg.IDREGISTRADOR
FROM SERVICIOHOTELCOMPLEMENTARIO shc
INNER JOIN CUENTASERVICIO cs ON  shc.IDSCOMPLEMENTARIO = cs.IDSERVICIOCOMPLEMENTARIO
INNER JOIN CUENTA cu ON cs.IDCUENTA = cu.IDCUENTA 
INNER JOIN RESERVA re ON re.IDRESERVA = cu.IDRESERVA
INNER JOIN HORARIO hor ON hor.IDHORARIO = re.IDHORARIO  
INNER JOIN REGISTRO reg ON reg.IDRESERVA = re.IDRESERVA 
WHERE COUNT(cs.IDSERVICIOCOMPLEMENTARIO) > ? AND shc.NOMBRESERVICIO = ? AND cu.VALOR > ? AND cu.VALOR < ? AND hor.FECHAINICIO < ? AND hor.FECHAFINAL > ? AND reg.IDREGISTRADOR = ?
