SELECT SUM(cu.VALOR)
FROM CLIENTE cli
INNER JOIN cu ON cli.IDCLIENTE = cu.IDCLIENTE
INNER JOIN RESERVA ON re.IDCUENTA = cu.IDCUENTA
INNER JOIN HORARIO ON hor.IDHORARIO = re.IDHORARIO
WHERE IDCLIENTE = ? AND hor.FECHAINICIO <= ? AND hor.FECHAFINAL >= ?
