SELECT ha.IDHABITACION AS NUMHABITACION, (sa.CANTIDADPERSONAS/ha.CAPACIDADHABITACION) AS INDICE
FROM HABITACION ha
INNER JOIN SERVICIOALOJAMIENTOHABITACION sah ON sah.IDHABITACION = ha.IDHABITACION
INNER JOIN SERVICIOALOJAMIENTO sa ON sa.IDSERVICIOALOJAMIENTO = sah.IDSERVICIOALOJAMIENTO
