INSERT INTO HORARIO(IDHORARIO,fechainicio,FECHAFINAL)
VALUES (1234, TO_DATE('17/02/19', 'DD/MM/YY'), TO_DATE('25/02/19', 'DD/MM/YY'));

INSERT INTO USUARIO (IDUSUARIO,ROL,CORREOELECTRONICO, NUMERODOCUMENTO,TIPODOCUMENTO)
VALUES (4545,'OrganizadorEventos','elcorreito123@gmail.com',12347654999,'pasaporte');

INSERT INTO CONVENCION (IDCONVENCION, IDHOTEL,NUMPARTICIPANTES, NOMBRECONVENCION, IDHORARIO)
VALUES (001,123, 5, 'Comicon',1234);

INSERT INTO CUENTA (IDCUENTA)
VALUES (1010101);


------------EN UN LOOP EN EL FRONT-------------
INSERT INTO HABITACION (IDHABITACION, TIPOHABITACION ,COSTONOCHE, CAPACIDADHABITACION, IDHOTEL, NUMEROHABITACION)
VALUES (1,'Sencilla', 40000, 1, 123,601);

INSERT INTO SERVICIOALOJAMIENTO (IDSERVICIOALOJAMIENTO,IDCUENTA, CANTIDADPERSONAS)
VALUES (123456, 1010101, 1);

INSERT INTO SERVICIOALOJAMIENTOHABITACION (IDHABITACION,IDALOJAMIENTO)
VALUES (1, 123456);

INSERT INTO CONVENCIONHABITACION (IDHABITACION, IDCONVENCION)
VALUES (1,001);

INSERT INTO RESERVA (IDRESERVA, ABONO, IDHABITACION, IDHORARIO, IDCLIENTE, IDHOTEL,idcuenta)
VALUES (01, 0, 1, 1234,4545,123,1010101);

--------------SERVICIOS ASOCIADOS A CONVENCION--------------

INSERT INTO convencionrestbarcafeteria (IDSERVICIOI, IDCONVENCION)
VALUES (952,001);

INSERT INTO convencionrestbarcafeteria (IDSERVICIOI, IDCONVENCION)
VALUES (953,001);

INSERT INTO convencionrestbarcafeteria (IDSERVICIOI, IDCONVENCION)
VALUES (954,001);

INSERT INTO CONVENCIONSALON (IDSALON, IDCONVENCION)
VALUES (959,001);
--------------------------------------------------------------


INSERT INTO registro (idregistro, estadocheckin,estadocheckout)
VALUES (0202,'E','F');