----LOOP----
INSERT INTO HABITACION (IDHABITACION, TIPOHABITACION ,COSTONOCHE, CAPACIDADHABITACION, IDHOTEL, NUMEROHABITACION)
VALUES (111,'Doble', 45000, 2, 123,111);

INSERT INTO SERVICIOHOTELCOMPLEMENTARIO (IDSCOMPLEMENTARIO, NOMBRESERVICIO,IDHOTEL) 
VALUES (999, 'Dotacion', 123);

INSERT INTO DOTACION (IDDOTACION,NOMBREOBJETO,ESCOBRABLE,VALOROBJETO,IDHABITACION)
VALUES (999, 'Televisor', 'S',3000,111);

UPDATE HABITACION 
SET DISPONIBLE = 'N'
WHERE IDHABITACION = 1;

INSERT INTO SERVICIOHOTELCOMPLEMENTARIO (IDSCOMPLEMENTARIO, NOMBRESERVICIO,IDHOTEL) 
VALUES (1, 'mantenimiento', 123);

INSERT INTO servicioarreglo (idservicio, iddotacion, idhabitacion, tipoarreglo)
VALUES (1,999,111,'mantenimiento');

DELETE FROM SERVICIOALOJAMIENTO 
WHERE idservicioalojamiento = (SELECT idservicioalojamiento FROM SERVICIOALOJAMIENTOHABITACION WHERE IDHABITACION = 111);

INSERT INTO HABITACION (IDHABITACION, TIPOHABITACION ,COSTONOCHE, CAPACIDADHABITACION, IDHOTEL, NUMEROHABITACION, DISPONIBLE)
VALUES (2,'VIP', 40000, 1, 123,601,'S');

INSERT INTO SERVICIOALOJAMIENTO (IDSERVICIOALOJAMIENTO,IDCUENTA, CANTIDADPERSONAS)
VALUES (123456, 1010101, 1);

INSERT INTO SERVICIOALOJAMIENTOHABITACION (IDHABITACION,IDALOJAMIENTO)
VALUES (2, 123456);
