DELETE FROM RESERVA 
WHERE IDHORARIO = (SELECT IDHORARIO FROM CONVENCION WHERE IDCONVENCION = 001);

DELETE FROM SERVICIOALOJAMIENTOHABITACION
WHERE IDSERVICIOALOJAMIENTO = (SELECT IDSERVICIOALOJAMIENTO FROM SERVICIOALOJAMIENTO WHERE IDCUENTA = 1010101);

DELETE FROM SERVICIOALOJAMIENTO 
WHERE IDCUENTA = 1010101;

DELETE FROM CONVENCIONHABITACION 
WHERE IDCONVENCION = 001;

DELETE FROM convencionrestbarcafeteria 
WHERE IDCONVENCION = 001;

DELETE FROM CONVENCIONSALON 
WHERE IDCONVENCION = 001;
