INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('Cedula',99070203770, 'Camilalonart@gmail.com', 'Gerente', 1000);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('Cedula',3456787654, 'Juandango@gmail.com', 'Administrador', 1456);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('Cedula',45338347754, 'elpepitoperez@gmail.com', 'Empleado', 1416);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('CedulaExtrajera',99999947754, 'blablabla@gmail.com', 'Empleado', 1111);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('TarjetaDeIdentidad',9998880714, 'camilita123@gmail.com', 'Empleado', 1123);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('Cedula',9123456755, 'juandaniel54321@gmail.com', 'Empleado', 1100);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('Cedula',91200056755, 'soylarecepcionista@gmail.com', 'Recepcionista', 1900);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('CedulaExtranjera',912099996799, 'elcoco@gmail.com', 'Recepcionista', 1810);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('CedulaExtranjera',12345678, 'megustaelmaiz@gmail.com', 'Cliente', 9999);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('Cedula',120000678, 'correocliente1@gmail.com', 'Cliente', 9119);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('Cedula',876543233, 'elsolesamarillo@gmail.com', 'Cliente', 9120);

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('CedulaExtranjera',765678761, 'elcorreo123@gmail.com', 'Cliente', 9922);
