INSERT INTO HABITACION (IDHABITACION, TIPOHABITACION, costonoche,capacidadhabitacion,IDHOTEL)
VALUES (102,'Presidencial',500000,2,123);

INSERT INTO HABITACION (IDHABITACION, TIPOHABITACION, costonoche,capacidadhabitacion,IDHOTEL)
VALUES (209,'Recien Casados',400000,2,123);

INSERT INTO HABITACION (IDHABITACION, TIPOHABITACION, costonoche,capacidadhabitacion,IDHOTEL)
VALUES (901,'Sencilla',80000,1,123);

INSERT INTO HABITACION (IDHABITACION, TIPOHABITACION, costonoche,capacidadhabitacion,IDHOTEL)
VALUES (801,'Doble',160000,2,123);

INSERT INTO HABITACION (IDHABITACION, TIPOHABITACION, costonoche,capacidadhabitacion,IDHOTEL)
VALUES (705,'Dos Sencillas',160000,2,123);