INSERT INTO PLAN (IDPLAN, NOMBREPLAN, TIPO)
VALUES (7885, 'Todo Incluido', 'Tiempo Completo');

INSERT INTO USUARIO (TIPODOCUMENTO, NUMERODOCUMENTO,CORREOELECTRONICO, ROL,IDUSUARIO)
VALUES ('Cedula',9944667722, 'holaholahola@gmail.com', 'Cliente', 1977);

INSERT INTO CUENTA (IDCUENTA, VALOR, METODODEPAGO, IDPLANCONSUMO, IDCLIENTE)
VALUES (555,900000, 'Efectivo', 7885, 1977);

INSERT INTO SERVICIOALOJAMIENTO (IDSERVICIOALOJAMIENTO, CANTIDADPERSONAS, IDCUENTA)
VALUES (234, 2, 555);

INSERT INTO CARACTERISTICAADICIONAL (IDCARACTERISTICA, LIMITE, DCTO)
VALUES (765, 3, '0');

INSERT INTO CARACTERISTICASERVICIO (idcaracteristica,idservcio,nombrecaracteristica,descripcion)
VALUES (765,1789,'3 cervezas','3 cervezas diarias');

INSERT INTO CUENTASERVICIO (IDCUENTA, IDSERVICIOCOMPLEMENTARIO)
VALUES (555,8701);

INSERT INTO CUENTASERVICIO (IDCUENTA, IDSERVICIOCOMPLEMENTARIO)
VALUES (555,6666);

INSERT INTO CUENTASERVICIO (IDCUENTA, IDSERVICIOCOMPLEMENTARIO)
VALUES (555,2121);

INSERT INTO CUENTASERVICIO (IDCUENTA, IDSERVICIOCOMPLEMENTARIO)
VALUES (555,1789);

INSERT INTO CUENTAALOJAMIENTO (IDCUENTA, IDSERVICIOALOJAMIENTO)
VALUES (555,234);

