INSERT INTO CUENTA (IDCUENTA, VALOR, METODODEPAGO, IDCLIENTE)
VALUES (409,200000, 'Efectivo', 9999);

INSERT INTO SERVICIOHOTELCOMPLEMENTARIO (IDSCOMPLEMENTARIO, NOMBRESERVICIO, IDHOTEL)
VALUES (6161,'ServLavado',123);

INSERT INTO SERVICIOLAVANDERIA (IDSERVICIO,NOMBRE,NOMBRESERVICIO,DESCRIPCION,TIPO,COSTOUNITARIO,CANTUNIDADES)
VALUES (6161,' ','Lavado de camisas','Se lavan las medias con poco jabon', 'lavado', 2000,1);

INSERT INTO CUENTASERVICIO (IDCUENTA, IDSERVICIOCOMPLEMENTARIO)
VALUES (409,6161);

INSERT INTO RESERVA (IDRESERVA,ABONO,IDHABITACION,IDHORARIO,IDCLIENTE,IDHOTEL,IDCUENTA)
VALUES(98765,10000,705,39,9999,123,409)